### ISSUE TITLE
Black brackets on vscode 1.9

### ISSUE THREAD

**Issue by twop** [drywolf/dark-plus-plus-theme#1]
![image](https://cloud.githubusercontent.com/assets/6633216/22874701/7b035936-f17c-11e6-9ace-018cf861a7f4.png)

**Comment by drywolf** [comment]
Thanks for the report, I will look into it.

**Comment by drywolf** [comment]
@twop I just published v0.0.8 which should fix this and be compatible with VSCode 1.9+

**Comment by twop** [comment]
Fixed. thanks!
